name: Gradientor
author: kopipejst
category: Widgets
tags: [gradient,colors]
docs: http://workshop.rs/2010/02/moobargraph-ajax-graph-for-mootools/
demo: http://workshop.rs/projects/gradientor/
current: 1.0
